name: fpl2_0
description: Flutter Participants Lottery v2.0

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.0-134.5.beta <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  provider: ^6.0.2
  about: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
  assets:
    - LICENSE.md
    - README.md