name: fpl2_0
description: A participants lottery and a timer for devs\' daily scrum meetings.

publish_to: 'none'

version: 2.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  provider: ^6.0.3
  about: ^2.1.1
  circular_countdown_timer: ^0.2.1
  google_fonts: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - LICENSE.md
    - README.md
    - assets/images/lumihiutale.png