name: fpl2_0
description: A participants lottery and a timer for devs\' daily scrum meetings.

publish_to: 'none'

version: 2.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  about: ^2.1.1
  circular_countdown_timer: ^0.2.3
  google_fonts: ^3.0.1
  get: ^4.6.5
  emoji_alert: ^1.1.0
  get_storage: ^2.0.3
  random_avatar: ^0.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true
  assets:
    - LICENSE.md
    - README.md